### PR TITLE
Appendices

### PR DESCRIPTION
**Pull request by lucasgautheron**
Can we make a list of what you think is interesting?

- [x] Impact of the length of clips and of the sampling method on relative errors
- [x] Impact of the length of clips on correlation counts
- [ ] Impact of awareness effect
- [x] Accuracy-computation time trade off
- [ ] Hardware vs accuracy
- [ ] Need for several recording days
- [ ] What more?

### CODE REVIEW

**Comment by alecristia** [comment]
I've also gotten questions about efficiency of the VTC/ALICE pipelines, including ​how fast can you get an idea of these numbers for a given recording? Do you need to analyze the whole rec or can you get away with subsampling? And in both cases, how long does it take to process a recording? Once we have length of audio that needs to be processed, then we can get processing time with Marvin's estimation in table 1 [in the vtc docs](https://github.com/MarvinLvn/voice-type-classifier/blob/new_model/docs/evaluations.md

Another one people ask is: should I record 1 full day or more than 1 day? Not sure we can really address this one with the current data.

Another is: is there any evidence that people habituate to the recording device, and if so, how long does it take them? Assuming that stress/knowledge of being recorded leads them to attend more to the child & talk more, this would predict higher voc rates in the first XX minutes or hours than in other places (knowing that often the end of 16h rec started at 9am is night time, so there will be a lot of silence anyway).

Yet another is: is the quality of the estimations lower for USBs than LENA or olympus? Unclear whether we can address this one either.

I'll think some more!

**Comment by lucasgautheron** [comment]
> I've also gotten questions about efficiency of the VTC/ALICE pipelines, including ​how fast can you get an idea of these numbers for a given recording? Do you need to analyze the whole rec or can you get away with subsampling? And in both cases, how long does it take to process a recording? Once we have length of audio that needs to be processed, then we can get processing time with Marvin's estimation in table 1 [in the vtc docs](https://github.com/MarvinLvn/voice-type-classifier/blob/new_model/docs/evaluations.md

Interesting. Should not be so difficult since I already have all the data I need to measure accuracy vs the amount of annotated audio. However the choice of the metric is a bit arbitrary.

> Another one people ask is: should I record 1 full day or more than 1 day? Not sure we can really address this one with the current data.
> 

What do you have in mind? test-rest reliability ?

> Another is: is there any evidence that people habituate to the recording device, and if so, how long does it take them? Assuming that stress/knowledge of being recorded leads them to attend more to the child & talk more, this would predict higher voc rates in the first XX minutes or hours than in other places (knowing that often the end of 16h rec started at 9am is night time, so there will be a lot of silence anyway).
> 

I think this one is actually difficult.

How do you know that a potential increase in voc counts in the first minutes is not due to daily seasonality and can be attributed to awareness of being recorded ?

I can see two ways in which daily seasonality could manifest itself:

 - As a function of clock time
 - As a function of time elapsed since the beginning of the recording (people may have the same daily patterns but with a random offset)
 
 The former could be separated from the awareness effect, but the latter is clearly confounded. And yet I could see reason why seasonality may be (to some extent) a function of the time elapsed since the beginning of recording: (e.g. people waking up and going to bed later).


> Yet another is: is the quality of the estimations lower for USBs than LENA or olympus? Unclear whether we can address this one either.
> 
> I'll think some more!

If we'd like to control for the corpus, than I can't think of any dataset apart from tsimane - but there may not be enough data.
If we'd like to control e.g. for the language, then there might be more that I don't know about?

**Comment by alecristia** [comment]
> > Another one people ask is: should I record 1 full day or more than 1 day? Not sure we can really address this one with the current data.
> 
> What do you have in mind? test-rest reliability ?

Well, they wonder how trustworthy metrics from one rec day are. Their intuition is that perhaps one day you have a flu, or the visit of a chatty friend -- so it may be better to record 2x or 4x or ... The only similar analysis comes from Gilkerson et al. 2017:

> Patterns of Variability Within Families
The within-family stability of LENA measures across multiple monthly recordings contributed during Phase I
is summarized in Table 3. We compared count values col- lected from 1 to 4 months apart. Because not all partici- pants contributed usable recordings each month, averaged Pearson correlations were weighted by sample size to compare counts between recordings over different time spans. Bonferroni correction values for alpha based on
the number of comparisons of each time span are shown
in Table 3. Correlations between recordings collected from 4 to 16 weeks apart decrease with time but indicate that caregiver and child vocal behavior as characterized by the automated system is moderately consistent across these time intervals. Although AWCs correlate at lower levels than the other two measures, suggesting greater month- to-month variability, paired sample t tests comparing mean count values for all contiguous months (e.g., 1 vs. 2, 2 vs. 3) revealed only one significant month-to-month difference (unadjusted for multiple testing and out of five possible comparisons) between months 4 and 5, mean difference= 1,657 (SD = 5,946), t(244) = 4.36, p < .001.
To examine daily variation within families on LENA metrics, during Phase I a subset of 52 participants was randomly selected to record a second time in addition to their once monthly schedule on the day following a regu- lar recording. As shown in Table 3, AWCs were positively correlated to a stronger degree than for recordings one
or more months apart. However, average daily AWCs var- ied approximately 12% between the first (M = 13,626,SD = 6,494) and second (M = 12,006, SD = 4,575) record- ing days, t(51) = 2.38, p = .02. CVCs for successive days correlated similarly to those from recordings taken 1–3 months apart and, on average, differed only marginally (M1 = 1,557, SD1 = 807; M2 = 1,723, SD2 = 828) between days, t(51) = 1.80, p = .08. Average daily turn counts for the 2 days (M1 = 382, SD1 = 259; M2 = 387, SD2 = 206) differed only by 1%, t(51) = 0.14, p = .89, though the correlation be- tween days was slightly lower than for recordings collected over longer spans. Analyses conducted controlling for child age yielded similar results. In summary, these results in- dicate that LENA measures on average are stable to a moderately high degree over time, but individual families may demonstrate day-to-day variability in their language behavior. We did not examine the impact of situational factors that would be likely to have an effect.

**Comment by alecristia** [comment]
> > Another is: is there any evidence that people habituate to the recording device, and if so, how long does it take them? Assuming that stress/knowledge of being recorded leads them to attend more to the child & talk more, this would predict higher voc rates in the first XX minutes or hours than in other places (knowing that often the end of 16h rec started at 9am is night time, so there will be a lot of silence anyway).
> 
> I think this one is actually difficult.
> 
> How do you know that a potential increase in voc counts in the first minutes is not due to daily seasonality and can be attributed to awareness of being recorded ?
> 
> I can see two ways in which daily seasonality could manifest itself:
> 
> * As a function of clock time
> * As a function of time elapsed since the beginning of the recording (people may have the same daily patterns but with a random offset)
> 
> The former could be separated from the awareness effect, but the latter is clearly confounded. And yet I could see reason why seasonality may be (to some extent) a function of the time elapsed since the beginning of recording: (e.g. people waking up and going to bed later).

We can use tsimane and png2019 for this, since some of the children were recorded twice, once with the rec started in the AM, the other in the PM. So that would work to decorrelate clock time from rec-onset-time, right?

**Comment by alecristia** [comment]
so in sum, we are left with 2 that are unanswerable with the current datasets, and that we cannot model/do simulations for at present: 

- quality of data
- how many days you need to capture true individual variation in traits rather than states:
source: https://www.oxford-review.com/oxford-review-encyclopaedia-terms/the-difference-between-an-state-and-a-trait/
> People often get confused about the difference between a trait and a state. In psychology and particularly work psychology there are clear distinctions between a state and a trait:
1. A trait is considered to be something that is part of an individuals personality and therefore a long term characteristic of an individual that shows through their behaviour, actions and feelings. It seen as being a characteristic, feature or quality of an individual. For example someone who says ‘I am a confident person’ or ‘I am just an anxious person’ is stating that is these attributes are part of who they are.
2. A state on the other hand is a temporary condition that they are experiencing for a short period of time. After the state has passes they will return to another condition. For example someone who says ‘I am feeling quite confident about this interview’ or ‘I feel nervous about doing this’ are describing states.
However working out what is really a trait and what is a state can often be difficult and is the content of much scientific argument at times.

**Comment by lucasgautheron** [comment]
> > > Another one people ask is: should I record 1 full day or more than 1 day? Not sure we can really address this one with the current data.
> > 
> > 
> > What do you have in mind? test-rest reliability ?
> 
> Well, they wonder how trustworthy metrics from one rec day are. Their intuition is that perhaps one day you have a flu, or the visit of a chatty friend -- so it may be better to record 2x or 4x or ... The only similar analysis comes from Gilkerson et al. 2017:
> 
> > Patterns of Variability Within Families
> > The within-family stability of LENA measures across multiple monthly recordings contributed during Phase I
> > is summarized in Table 3. We compared count values col- lected from 1 to 4 months apart. Because not all partici- pants contributed usable recordings each month, averaged Pearson correlations were weighted by sample size to compare counts between recordings over different time spans. Bonferroni correction values for alpha based on
> > the number of comparisons of each time span are shown
> > in Table 3. Correlations between recordings collected from 4 to 16 weeks apart decrease with time but indicate that caregiver and child vocal behavior as characterized by the automated system is moderately consistent across these time intervals. Although AWCs correlate at lower levels than the other two measures, suggesting greater month- to-month variability, paired sample t tests comparing mean count values for all contiguous months (e.g., 1 vs. 2, 2 vs. 3) revealed only one significant month-to-month difference (unadjusted for multiple testing and out of five possible comparisons) between months 4 and 5, mean difference= 1,657 (SD = 5,946), t(244) = 4.36, p < .001.
> > To examine daily variation within families on LENA metrics, during Phase I a subset of 52 participants was randomly selected to record a second time in addition to their once monthly schedule on the day following a regu- lar recording. As shown in Table 3, AWCs were positively correlated to a stronger degree than for recordings one
> > or more months apart. However, average daily AWCs var- ied approximately 12% between the first (M = 13,626,SD = 6,494) and second (M = 12,006, SD = 4,575) record- ing days, t(51) = 2.38, p = .02. CVCs for successive days correlated similarly to those from recordings taken 1–3 months apart and, on average, differed only marginally (M1 = 1,557, SD1 = 807; M2 = 1,723, SD2 = 828) between days, t(51) = 1.80, p = .08. Average daily turn counts for the 2 days (M1 = 382, SD1 = 259; M2 = 387, SD2 = 206) differed only by 1%, t(51) = 0.14, p = .89, though the correlation be- tween days was slightly lower than for recordings collected over longer spans. Analyses conducted controlling for child age yielded similar results. In summary, these results in- dicate that LENA measures on average are stable to a moderately high degree over time, but individual families may demonstrate day-to-day variability in their language behavior. We did not examine the impact of situational factors that would be likely to have an effect.

No similar study was done with ramirez-esparza's corpus? It should be great for that. It has 4 recordings the same week (two on week days, two on the week-end)

[Log into GIN to see the plot](https://gin.g-node.org/EL1000/metrics/raw/master/plots/children_age_coverage.png?raw=true)

**Comment by lucasgautheron** [comment]
> > > Another is: is there any evidence that people habituate to the recording device, and if so, how long does it take them? Assuming that stress/knowledge of being recorded leads them to attend more to the child & talk more, this would predict higher voc rates in the first XX minutes or hours than in other places (knowing that often the end of 16h rec started at 9am is night time, so there will be a lot of silence anyway).
> > 
> > 
> > I think this one is actually difficult.
> > How do you know that a potential increase in voc counts in the first minutes is not due to daily seasonality and can be attributed to awareness of being recorded ?
> > I can see two ways in which daily seasonality could manifest itself:
> > 
> > * As a function of clock time
> > * As a function of time elapsed since the beginning of the recording (people may have the same daily patterns but with a random offset)
> > 
> > The former could be separated from the awareness effect, but the latter is clearly confounded. And yet I could see reason why seasonality may be (to some extent) a function of the time elapsed since the beginning of recording: (e.g. people waking up and going to bed later).
> 
> We can use tsimane and png2019 for this, since some of the children were recorded twice, once with the rec started in the AM, the other in the PM. So that would work to decorrelate clock time from rec-onset-time, right?

Right, having a look into it

**Comment by alecristia** [comment]
> > > > Another one people ask is: should I record 1 full day or more than 1 day? Not sure we can really address this one with the current data.
> > > 
> > > 
> > > What do you have in mind? test-rest reliability ?
> > 
> > 
> > Well, they wonder how trustworthy metrics from one rec day are. Their intuition is that perhaps one day you have a flu, or the visit of a chatty friend -- so it may be better to record 2x or 4x or ... The only similar analysis comes from Gilkerson et al. 2017:
> > > Patterns of Variability Within Families
> > > The within-family stability of LENA measures across multiple monthly recordings contributed during Phase I
> > > is summarized in Table 3. We compared count values col- lected from 1 to 4 months apart. Because not all partici- pants contributed usable recordings each month, averaged Pearson correlations were weighted by sample size to compare counts between recordings over different time spans. Bonferroni correction values for alpha based on
> > > the number of comparisons of each time span are shown
> > > in Table 3. Correlations between recordings collected from 4 to 16 weeks apart decrease with time but indicate that caregiver and child vocal behavior as characterized by the automated system is moderately consistent across these time intervals. Although AWCs correlate at lower levels than the other two measures, suggesting greater month- to-month variability, paired sample t tests comparing mean count values for all contiguous months (e.g., 1 vs. 2, 2 vs. 3) revealed only one significant month-to-month difference (unadjusted for multiple testing and out of five possible comparisons) between months 4 and 5, mean difference= 1,657 (SD = 5,946), t(244) = 4.36, p < .001.
> > > To examine daily variation within families on LENA metrics, during Phase I a subset of 52 participants was randomly selected to record a second time in addition to their once monthly schedule on the day following a regu- lar recording. As shown in Table 3, AWCs were positively correlated to a stronger degree than for recordings one
> > > or more months apart. However, average daily AWCs var- ied approximately 12% between the first (M = 13,626,SD = 6,494) and second (M = 12,006, SD = 4,575) record- ing days, t(51) = 2.38, p = .02. CVCs for successive days correlated similarly to those from recordings taken 1–3 months apart and, on average, differed only marginally (M1 = 1,557, SD1 = 807; M2 = 1,723, SD2 = 828) between days, t(51) = 1.80, p = .08. Average daily turn counts for the 2 days (M1 = 382, SD1 = 259; M2 = 387, SD2 = 206) differed only by 1%, t(51) = 0.14, p = .89, though the correlation be- tween days was slightly lower than for recordings collected over longer spans. Analyses conducted controlling for child age yielded similar results. In summary, these results in- dicate that LENA measures on average are stable to a moderately high degree over time, but individual families may demonstrate day-to-day variability in their language behavior. We did not examine the impact of situational factors that would be likely to have an effect.
> 
> No similar study was done with ramirez-esparza's corpus? It should be great for that. It has 4 recordings the same week (two on week days, two on the week-end)
> 
> [Log into GIN to see the plot](https://gin.g-node.org/EL1000/metrics/raw/master/plots/children_age_coverage.png?raw=true)

great idea! I'll ask her

**Pull request merged**
